### ISSUE TITLE
FRONTEND: Create a design sketch

### ISSUE THREAD

**Issue by sergejparity** [sergejparity/voteabout#5]
Idea of this issue is to have a discussion about  frontpage of a dApp.
* which elements should we have on page?
* vote creation page?
* voting page
* ???

**Comment by MrkielCode** [comment]
1. Create proposal page
2. Home page (little description of the app and  and status)
3. Proposal page (with parameter of a particular vote Id)

**Comment by tumutech** [comment]
![Vote About Sketch](https://github.com/user-attachments/assets/d22fb40f-604b-4254-a491-9f93939f4e4e)
  
We can have these pages:
Landing page: including a description  VoteAbout DApp with option to get started by connecting wallet
Dashboard page(accessible only to users  after connecting wallet): Having a menu with option to create Poll(Proposal)
It shows a list of the most recent polls
Poll Details: After someone clicking on a poll from the above list, they can see results(if poll was closed) or show poll name, candidates allowing the user to vote vote
Create Poll: Used to create a poll or proposal by adding candidates(options) setiing vallidity and then publishing the poll.

Consider the attached image, for the flow, and any guidance on what to consider,,,
Also can we call them proposals or polls?

**Comment by tumutech** [comment]
I had started on the create poll page earlier, let me commit the progress so that you can make adjustments on it,
these were not yet done:

1. restricting start date to not allow current date on wards
2. making the end date to be a date not before the start date

![poll create](https://github.com/user-attachments/assets/c0a4b18f-033e-452d-9599-1b434c313e50)

**Comment by tumutech** [comment]
the front-end sketch was completed
